server.port=8081
spring.application.name=st-auth

spring.profiles.active=dev

jwt.secret=VGhpc0lzQVN0cm9uZ1NlY3JldEtleUZvckp3dFRva2VuMTIzNDU2Nzg5MDEyMzQ=
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=skillstute.com@gmail.com
spring.mail.password=hppl ubpp xwae vsyt
#Yashvi@9712
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true